{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unifabric.controllerName" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: unifabric-controller
data:
  controller.yaml: |-
    {{- $controllerConfig := deepCopy .Values.controller.config }}
    {{- if hasKey .Values "topologyLabels" }}
    {{- $_ := set $controllerConfig "topologyLabels" .Values.topologyLabels }}
    {{- end }}
    {{- if hasKey .Values "nodeTopologyDiscovery" }}
    {{- $_ := set $controllerConfig "nodeTopologyDiscovery" .Values.nodeTopologyDiscovery }}
    {{- end }}
    {{- if hasKey .Values "switchTopologyDiscovery" }}
    {{- $switchDiscoveryConfig := deepCopy .Values.switchTopologyDiscovery }}
    {{- if hasKey .Values "topologyGroupNaming" }}
    {{- $_ := set $switchDiscoveryConfig "groupNaming" .Values.topologyGroupNaming }}
    {{- end }}
    {{- $_ := set $controllerConfig "scaleOutDiscovery" (dict "switches" $switchDiscoveryConfig) }}
    {{- end }}
    {{- include "unifabric.render" (dict "value" $controllerConfig "context" $) | nindent 4 }}
{{- end }}
---
{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unifabric.agentName" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: unifabric-agent
data:
  agent.yaml: |-
    {{- $agentConfig := deepCopy .Values.agent.config }}
    {{- if hasKey .Values "nodeTopologyDiscovery" }}
    {{- $_ := set $agentConfig "nodeTopologyDiscovery" .Values.nodeTopologyDiscovery }}
    {{- end }}
    {{- include "unifabric.render" (dict "value" $agentConfig "context" $) | nindent 4 }}
{{- end }}
---
{{- if and .Values.agent.enabled .Values.agent.lldp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unifabric.agentName" . }}-lldpd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: unifabric-agent
data:
  lldpd.conf: |
    {{- if .Values.agent.lldp.managementIPPattern }}
    configure system ip management pattern {{ .Values.agent.lldp.managementIPPattern }}
    {{- end }}
    {{- if .Values.agent.lldp.interfaces }}
    configure system interface pattern {{ .Values.agent.lldp.interfaces }}
    {{- end }}
    {{- if .Values.agent.lldp.txInterval }}
    configure lldp tx-interval {{ .Values.agent.lldp.txInterval }}
    {{- end }}
    {{- if .Values.agent.lldp.extraConfig }}
    {{ .Values.agent.lldp.extraConfig }}
    {{- end }}
{{- end }}
