sflow {
  agent = eth0

  polling = 0

  sampling = 400
  sampling.100M = 100
  sampling.1G = 1000
  sampling.10G = 10000
  sampling.25G = 25000
  sampling.40G = 40000
  sampling.50G = 50000
  sampling.100G = 100000
  sampling.200G = 200000
  sampling.400G = 400000
  sampling.800G = 800000

  collector { ip=192.168.200.6 udpport=30936 dev=eth0 }

  psample { group = 1 }
  # dent { sw = on switchport = ^swp[0-9]+$ }
}
