#!/bin/bash

set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
CONTROLLER_GEN=${CONTROLLER_GEN:-"${ROOT_DIR}/hack/controller-gen.sh"}
WORK_ROOT="${ROOT_DIR}/.tmp"

mkdir -p "${WORK_ROOT}"
WORK_DIR=$(mktemp -d "${WORK_ROOT}/rbac.XXXXXX")
trap 'rm -rf "${WORK_DIR}"' EXIT

generate_role() {
  local component=$1
  local package=$2
  local output=$3
  local generated_dir="${WORK_DIR}/${component}"
  local generated_role="${generated_dir}/role.yaml"

  mkdir -p "${generated_dir}"
  "${CONTROLLER_GEN}" \
    "rbac:roleName=unifabric-${component}" \
    "paths=${package}" \
    "output:dir=${generated_dir}"

  if ! grep -q '^rules:' "${generated_role}"; then
    echo "generated RBAC for ${component} has no rules" >&2
    exit 1
  fi

  {
    cat <<EOF
{{/*
Code generated by hack/generate-rbac.sh. DO NOT EDIT.
*/}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "unifabric.${component}Name" . }}
  labels:
    {{- include "unifabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: unifabric-${component}
EOF
    sed -n '/^rules:/,$p' "${generated_role}"
  } > "${output}.tmp"

  mv "${output}.tmp" "${output}"
}

generate_role controller "${ROOT_DIR}/cmd/controller" "${ROOT_DIR}/chart/templates/ControllerRole.yaml"
generate_role agent "${ROOT_DIR}/cmd/agent" "${ROOT_DIR}/chart/templates/AgentRole.yaml"