// Copyright 2026 Authors of unifabric-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pkg/switchagent/switchreporter.proto

package switchagent

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SwitchReporter_WatchLLDPNeighbors_FullMethodName = "/unifabric.switchagent.v1.SwitchReporter/WatchLLDPNeighbors"
)

// SwitchReporterClient is the client API for SwitchReporter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwitchReporterClient interface {
	WatchLLDPNeighbors(ctx context.Context, in *WatchLLDPNeighborsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LLDPNeighborSnapshot], error)
}

type switchReporterClient struct {
	cc grpc.ClientConnInterface
}

func NewSwitchReporterClient(cc grpc.ClientConnInterface) SwitchReporterClient {
	return &switchReporterClient{cc}
}

func (c *switchReporterClient) WatchLLDPNeighbors(ctx context.Context, in *WatchLLDPNeighborsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LLDPNeighborSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SwitchReporter_ServiceDesc.Streams[0], SwitchReporter_WatchLLDPNeighbors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchLLDPNeighborsRequest, LLDPNeighborSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwitchReporter_WatchLLDPNeighborsClient = grpc.ServerStreamingClient[LLDPNeighborSnapshot]

// SwitchReporterServer is the server API for SwitchReporter service.
// All implementations must embed UnimplementedSwitchReporterServer
// for forward compatibility.
type SwitchReporterServer interface {
	WatchLLDPNeighbors(*WatchLLDPNeighborsRequest, grpc.ServerStreamingServer[LLDPNeighborSnapshot]) error
	mustEmbedUnimplementedSwitchReporterServer()
}

// UnimplementedSwitchReporterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSwitchReporterServer struct{}

func (UnimplementedSwitchReporterServer) WatchLLDPNeighbors(*WatchLLDPNeighborsRequest, grpc.ServerStreamingServer[LLDPNeighborSnapshot]) error {
	return status.Errorf(codes.Unimplemented, "method WatchLLDPNeighbors not implemented")
}
func (UnimplementedSwitchReporterServer) mustEmbedUnimplementedSwitchReporterServer() {}
func (UnimplementedSwitchReporterServer) testEmbeddedByValue()                        {}

// UnsafeSwitchReporterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwitchReporterServer will
// result in compilation errors.
type UnsafeSwitchReporterServer interface {
	mustEmbedUnimplementedSwitchReporterServer()
}

func RegisterSwitchReporterServer(s grpc.ServiceRegistrar, srv SwitchReporterServer) {
	// If the following call pancis, it indicates UnimplementedSwitchReporterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SwitchReporter_ServiceDesc, srv)
}

func _SwitchReporter_WatchLLDPNeighbors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchLLDPNeighborsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SwitchReporterServer).WatchLLDPNeighbors(m, &grpc.GenericServerStream[WatchLLDPNeighborsRequest, LLDPNeighborSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SwitchReporter_WatchLLDPNeighborsServer = grpc.ServerStreamingServer[LLDPNeighborSnapshot]

// SwitchReporter_ServiceDesc is the grpc.ServiceDesc for SwitchReporter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwitchReporter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "unifabric.switchagent.v1.SwitchReporter",
	HandlerType: (*SwitchReporterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchLLDPNeighbors",
			Handler:       _SwitchReporter_WatchLLDPNeighbors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/switchagent/switchreporter.proto",
}
