// Copyright 2026 Authors of unifabric-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/switchagent/switchreporter.proto

package switchagent

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchLLDPNeighborsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExpectedSwitchName string                 `protobuf:"bytes,1,opt,name=expected_switch_name,json=expectedSwitchName,proto3" json:"expected_switch_name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WatchLLDPNeighborsRequest) Reset() {
	*x = WatchLLDPNeighborsRequest{}
	mi := &file_pkg_switchagent_switchreporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchLLDPNeighborsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchLLDPNeighborsRequest) ProtoMessage() {}

func (x *WatchLLDPNeighborsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_switchagent_switchreporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchLLDPNeighborsRequest.ProtoReflect.Descriptor instead.
func (*WatchLLDPNeighborsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_switchagent_switchreporter_proto_rawDescGZIP(), []int{0}
}

func (x *WatchLLDPNeighborsRequest) GetExpectedSwitchName() string {
	if x != nil {
		return x.ExpectedSwitchName
	}
	return ""
}

type LLDPNeighborSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwitchName    string                 `protobuf:"bytes,1,opt,name=switch_name,json=switchName,proto3" json:"switch_name,omitempty"`
	LldpNeighbors []*LLDPNeighbor        `protobuf:"bytes,2,rep,name=lldp_neighbors,json=lldpNeighbors,proto3" json:"lldp_neighbors,omitempty"`
	Generation    uint64                 `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLDPNeighborSnapshot) Reset() {
	*x = LLDPNeighborSnapshot{}
	mi := &file_pkg_switchagent_switchreporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLDPNeighborSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLDPNeighborSnapshot) ProtoMessage() {}

func (x *LLDPNeighborSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_switchagent_switchreporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLDPNeighborSnapshot.ProtoReflect.Descriptor instead.
func (*LLDPNeighborSnapshot) Descriptor() ([]byte, []int) {
	return file_pkg_switchagent_switchreporter_proto_rawDescGZIP(), []int{1}
}

func (x *LLDPNeighborSnapshot) GetSwitchName() string {
	if x != nil {
		return x.SwitchName
	}
	return ""
}

func (x *LLDPNeighborSnapshot) GetLldpNeighbors() []*LLDPNeighbor {
	if x != nil {
		return x.LldpNeighbors
	}
	return nil
}

func (x *LLDPNeighborSnapshot) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type LLDPNeighbor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LocalDeviceName  string                 `protobuf:"bytes,1,opt,name=local_device_name,json=localDeviceName,proto3" json:"local_device_name,omitempty"`
	LocalPort        string                 `protobuf:"bytes,2,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemoteSystemName string                 `protobuf:"bytes,3,opt,name=remote_system_name,json=remoteSystemName,proto3" json:"remote_system_name,omitempty"`
	RemotePortId     string                 `protobuf:"bytes,4,opt,name=remote_port_id,json=remotePortId,proto3" json:"remote_port_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LLDPNeighbor) Reset() {
	*x = LLDPNeighbor{}
	mi := &file_pkg_switchagent_switchreporter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLDPNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLDPNeighbor) ProtoMessage() {}

func (x *LLDPNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_switchagent_switchreporter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLDPNeighbor.ProtoReflect.Descriptor instead.
func (*LLDPNeighbor) Descriptor() ([]byte, []int) {
	return file_pkg_switchagent_switchreporter_proto_rawDescGZIP(), []int{2}
}

func (x *LLDPNeighbor) GetLocalDeviceName() string {
	if x != nil {
		return x.LocalDeviceName
	}
	return ""
}

func (x *LLDPNeighbor) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *LLDPNeighbor) GetRemoteSystemName() string {
	if x != nil {
		return x.RemoteSystemName
	}
	return ""
}

func (x *LLDPNeighbor) GetRemotePortId() string {
	if x != nil {
		return x.RemotePortId
	}
	return ""
}

var File_pkg_switchagent_switchreporter_proto protoreflect.FileDescriptor

const file_pkg_switchagent_switchreporter_proto_rawDesc = "" +
	"\n" +
	"$pkg/switchagent/switchreporter.proto\x12\x18unifabric.switchagent.v1\"M\n" +
	"\x19WatchLLDPNeighborsRequest\x120\n" +
	"\x14expected_switch_name\x18\x01 \x01(\tR\x12expectedSwitchName\"\xa6\x01\n" +
	"\x14LLDPNeighborSnapshot\x12\x1f\n" +
	"\vswitch_name\x18\x01 \x01(\tR\n" +
	"switchName\x12M\n" +
	"\x0elldp_neighbors\x18\x02 \x03(\v2&.unifabric.switchagent.v1.LLDPNeighborR\rlldpNeighbors\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x04R\n" +
	"generation\"\xad\x01\n" +
	"\fLLDPNeighbor\x12*\n" +
	"\x11local_device_name\x18\x01 \x01(\tR\x0flocalDeviceName\x12\x1d\n" +
	"\n" +
	"local_port\x18\x02 \x01(\tR\tlocalPort\x12,\n" +
	"\x12remote_system_name\x18\x03 \x01(\tR\x10remoteSystemName\x12$\n" +
	"\x0eremote_port_id\x18\x04 \x01(\tR\fremotePortId2\x8d\x01\n" +
	"\x0eSwitchReporter\x12{\n" +
	"\x12WatchLLDPNeighbors\x123.unifabric.switchagent.v1.WatchLLDPNeighborsRequest\x1a..unifabric.switchagent.v1.LLDPNeighborSnapshot0\x01B?Z=github.com/unifabric-io/unifabric/pkg/switchagent;switchagentb\x06proto3"

var (
	file_pkg_switchagent_switchreporter_proto_rawDescOnce sync.Once
	file_pkg_switchagent_switchreporter_proto_rawDescData []byte
)

func file_pkg_switchagent_switchreporter_proto_rawDescGZIP() []byte {
	file_pkg_switchagent_switchreporter_proto_rawDescOnce.Do(func() {
		file_pkg_switchagent_switchreporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_switchagent_switchreporter_proto_rawDesc), len(file_pkg_switchagent_switchreporter_proto_rawDesc)))
	})
	return file_pkg_switchagent_switchreporter_proto_rawDescData
}

var file_pkg_switchagent_switchreporter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_switchagent_switchreporter_proto_goTypes = []any{
	(*WatchLLDPNeighborsRequest)(nil), // 0: unifabric.switchagent.v1.WatchLLDPNeighborsRequest
	(*LLDPNeighborSnapshot)(nil),      // 1: unifabric.switchagent.v1.LLDPNeighborSnapshot
	(*LLDPNeighbor)(nil),              // 2: unifabric.switchagent.v1.LLDPNeighbor
}
var file_pkg_switchagent_switchreporter_proto_depIdxs = []int32{
	2, // 0: unifabric.switchagent.v1.LLDPNeighborSnapshot.lldp_neighbors:type_name -> unifabric.switchagent.v1.LLDPNeighbor
	0, // 1: unifabric.switchagent.v1.SwitchReporter.WatchLLDPNeighbors:input_type -> unifabric.switchagent.v1.WatchLLDPNeighborsRequest
	1, // 2: unifabric.switchagent.v1.SwitchReporter.WatchLLDPNeighbors:output_type -> unifabric.switchagent.v1.LLDPNeighborSnapshot
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_switchagent_switchreporter_proto_init() }
func file_pkg_switchagent_switchreporter_proto_init() {
	if File_pkg_switchagent_switchreporter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_switchagent_switchreporter_proto_rawDesc), len(file_pkg_switchagent_switchreporter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_switchagent_switchreporter_proto_goTypes,
		DependencyIndexes: file_pkg_switchagent_switchreporter_proto_depIdxs,
		MessageInfos:      file_pkg_switchagent_switchreporter_proto_msgTypes,
	}.Build()
	File_pkg_switchagent_switchreporter_proto = out.File
	file_pkg_switchagent_switchreporter_proto_goTypes = nil
	file_pkg_switchagent_switchreporter_proto_depIdxs = nil
}
